### ISSUE TITLE
Filebot guide is broken

### ISSUE THREAD

**Issue by DerSandmann-Badcode** [feralhosting/wiki#2]
It seems like file it references - http://app.filebot.net/data/exclude-blacklist.txt does not exist anymore, so following the guide won't work

The wiki has a broken link to a forum post about it https://www.feralhosting.com/faq/view?question=256

**Comment by userdocs** [comment]
There is no reference to that file in this article.

https://github.com/feralhosting/wiki/blob/f846a0698d0d169e9e02170a31d9d52e52959c60/09%20Linux%20Command-Line%20(Advanced)/15%20FileBot%20CLI%20-%20Basic%20Setup.md

What are you referring to exactly?

**Comment by userdocs** [comment]
closed for no response.
